language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - "sudo apt-get install zlib1g-dev libpng-dev libgif-dev 2>&1 | tail -n 4"
  - cpanm -nq Devel::Cover::Report::Coveralls
script:
  perl Build.PL && ./Build build && cover -test
after_success:
  - cover -report coveralls
notifications:
  irc:
    channels:
      - "irc.freenode.net#bayadev"
    on_success: change
    on_failure: always